

public class Menu extends javax.swing.JFrame {

    public boolean done = false; 
    private javax.swing.JLabel Fondo_Label;
    private javax.swing.JButton Iniciar_Button;
    private javax.swing.JLabel Menu_label;
    private javax.swing.JTextField Usuario_Campo;
    private javax.swing.JLabel Usuario_label;

    public Menu() {
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Menu_label = new javax.swing.JLabel();
        Usuario_label = new javax.swing.JLabel();
        Usuario_Campo = new javax.swing.JTextField();
        Iniciar_Button = new javax.swing.JButton();
        Fondo_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(700, 500, 500, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        Menu_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes_Menu/nameMenu.png"))); // NOI18N
        Menu_label.setOpaque(true);
        getContentPane().add(Menu_label);
        Menu_label.setBounds(70, 10, 560, 77);

        Usuario_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Usuario_label.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_label.setText("Usuario:");
        getContentPane().add(Usuario_label);
        Usuario_label.setBounds(50, 230, 180, 30);

        Usuario_Campo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Usuario_Campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_CampoActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario_Campo);
        Usuario_Campo.setBounds(230, 220, 280, 40);

        Iniciar_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes_Menu/startMenu.jpg"))); // NOI18N
        Iniciar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar_Button);
        Iniciar_Button.setBounds(240, 320, 260, 130);

        Fondo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes_Menu/BackMenu.jpg"))); // NOI18N
        Fondo_Label.setMaximumSize(new java.awt.Dimension(700, 500));
        Fondo_Label.setMinimumSize(new java.awt.Dimension(700, 500));
        Fondo_Label.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(Fondo_Label);
        Fondo_Label.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>                        

    private void Usuario_CampoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void Iniciar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code shere:
        done = true;
    }                                              

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    
    // End of variables declaration                   
}
